export default {
    Home: 'Dashboard' ,
    Profile: 'Profile' ,
    LogIn: 'Log in',
    Register: "Register",
    LogInWithFacebook: "Log in with Facebook",
    LogInwithGoogle: "Log in with Google",
    ForgotYourPassword: "Forgot your password?",
    Doyouwanttostartrightnow:	"Do you want to start right now?",
    PopularPrograms:	"Popular Programs",
    Programs:	"Programs",
    ChooseProgram:	"Choose Program",
    BrowsePrograms:	"Browse Programs",
    SelectYourprogram:	"Choose own program",
    YourProgram: "Your Program",
    MakeOwnProgram:	"Create own program",
    Gender:	"Gender",
    Level:	"Level", 
    PerWeek:	"per week",
    focus:	"Focus",
    Diary:	"Diary",
    Weight:	"Weight",
    ownWeight: "Own Weight",
    TotalWeight:	"Total Weight",
    maxWeight: "Record Weight",
    AverageWeight:	"Average Weight",
    Set: "Set",
    Sets: "Sets",
    Reps: "Reps",
    Total: "Total",
    HowLong: "Duration",
    YouhaveworkoutToday: "You have workout today",
    YouHaveRestDay: "You have rest day",
    Advice: "Advice",
    Addworkout:	"Add workout",
    Addactivity:	"Add Activity",
    Exercises: 	"Exercises",
    Exercise: "Exercise",
    ExercisesThisWeek: "Exercises this week",
    ExercisesLibrary: "Exercises",
    SearchExercises: "Browse Exercises",
    All: "All",
    totalDays: "Total Days",
    days: "Days",
    weeks: "Weeks",
    week: "Week",
    inWeek: "Week",
    muscles: "muscles",
    isolation:	"Isolation",
    basic:	"Basic",
    chest:	"Chest",
    back:	"Back",
    shoulders:	"Shoulders",
    biceps:	"Biceps",
    triceps:	"Triceps",
    abs:	"Abs",
    legs:	"Legs",
    glutes:	"Glutes",
    calves:	"Calves",
    Workouts: "Workouts",
    workoutsFinished:	"Workouts done",
    exersiscesFinished:	"Exercises finished",
    currentProgram:	"Current program",
    currentLevel:	"Current level",
    maximumWeight:	"Record weight",
    ViewStatistics:	"View statistics",
    AverageWorkoutTime:	"Average workout time",
    currentExercise:	"Current exercise",
    muscleGroup:	"Muscle group",
    upcomingExercise:	"Upcoming exercise",
    Previous: "Previous",
    NextWeek: "Next Week",
    Delete: "Delete",
    TotalExercises: "Total Exercises",
    Discover: "Discover",
    WePrepared: 'We prepared a programs that will fit your needs',
    DoneThisWeek: "Done this week",
    DoneThisDay: "Done this day",
    CustomExercises: "Custom exercise",
    ContinueProgram: "Continue program",
    NoData: "No Data Here",
    Logout: "Log out",
    ChangeWeight: "Change weight",
    LeaveProgram: "Leave program",
    LeaveProgramAlert: "You are about to end the program. Are you sure?",
    DiaryPromoTitle: "Record and track achievements",
    DiaryPromo: "A diary will show the statistics for each training day and will inform you about upcoming trainings",
    ExercisesPromoTitle: "Exercises Library",
    ExercisesPromoText: "Find the exercises according to the muscle groups and the type. Additionaly, we have videos, that will help you learn train effectively and safely",
    Cancel: "Cancel" ,
    Add: "Add",
    CheckOut: "Check Out",
    RandomAdvice: "Remember to stretch after the traing to keep muscles in a good shape",
    DailyAdvice: "Daily Advice",
    LoginPromo: "Learn how to train rationally with our library of exercises with explanatory videos.",
    Email: "Email",
    Password: "Password",
    EnterYourEmail: "Enter your email",
    EnterPassword: "Enter your password",
    EnterName: "Enter your name",
    Male: "Male",
    Female: "Female",
    male: 'male',
    female: 'female',
    both: 'both',
    exercisesDone: "Exercises done",
    TotalSets: "Total sets",
    TotalReps: "Toral reps",
    FeedbackText: "Please evaluate the difficulty of the training so that we can adjust the program for you",
    Next: "Next",
    Measurements: "Enter your details",
    HowManyWeeks: "How many days per week you want to train?",
    FillBasic: "Great! Fill the basic information below and you are ready!",
    Done: "Done",
    Height: "Height",
    Name: "Name",
    ExerciseName: "Exercise name",
    EnterExerciseName: "Enter exercise name",
    ProgramsPromo: "All programs are designed by professionals",
    First: "First",
    Second: "Second",
    Third: "Third",
    Fourth: "Fourth",
    Fifth: "Fifth",
    Sixth: "Sixth",
    Seventh: "Seventh",
    Day: "Day",
    WorkoutIsCompleted: "Workout is completed!",
    Feedback: "Feedback",
    Bad: "Hard",
    Fine: "Perfect",
    VeryGood: "Easy",
    SelectWorkoutDays: "Select Workout Days",
    ChooseAtWhatDays: "Please mark the workout days",
    Monday: "Monday",
    Tuesday: "Tuesday",
    Wednesday: "Wednesday",
    Thursday: "Thursday",
    Friday: "Friday",
    Saturday: "Saturday",
    Sunday: "Sunday",
    Save: "Save",
    
  
    EnrollToProgram: "Enroll to program",
    EditProgram: "Edit",
    DoneWorkoutToday: "You have finished workout today",
  
    //Exercises
    Superset: "Superset",
    ExerciseName: "Exercise name",
 
    SeatedCableRow:	"Seated cable row",
    Squats: "Squats",
    DeadLift:	"Dead lift",
    LatPulldown:	"Lat pull down",
    LegPress:	"Leg Press",
    BicepsCurl:	"Biceps curl",
    SmithMachineSquat: "Smith machine squat",
    LegCurls: "Leg curls",
    LegExtension:	"Leg extension",
    DumbbellShoulderPress: "Dumbbell shoulder press",
    MilitaryPress: "Military press",
    SideLaterals: "Side laterals",
    InclineDumbbellPress:	"Incline dumbbell press",
    DumbbellFly: "Dumbbell fly",
    CablePushdown: "Cable pushdown",
    RearLaterals: "Rear laterals",
    FlyesMachine: "Flyes",
    BenchPress:	"Bench press",
    FrenchCurls: "French curls",
    BentoverRow:	"Bentover row",
    CableCrunch: "Cable crunch",
    ConcentrationCurl:	"Concentration curl",
    Crunches:	"Crunches",
    LegRaises:	"Leg raises",
    DeadliftGlutes: "Deadlift Glutes",
    Abduction: "Abduction",
    Lunges: "Lunges",
    StandingCalfRaise:	"Standing calf raise",
    SeatedCalfRaise:	"Seated calf raise",
    GluteSquats:	"Glute Squats",

    others: 'others',
    all: 'all',
    ShowMore: "Show more",
    Hide: "Hide",
    CreateYourOwn: 'Create your own',

    ManageExercises: 'MANAGE EXERCISES',
    ManageExercisesPromo: 'Manage exercises by changing their order, adding new ones or combining them into exercise sets',
    Instructions: "Instructions",
    Cautions: "Cautions",
    Variations: "Variations",

    // Instructions, Cautions and Variations
    Instruction1: "Sit straight and keep your chest up. Pull the weight to the mid-section of your abs. Keep your elbows open.",
    Instruction2: "Keep your chest in good position with abdomen through exercise. For maximum thigh activation keep the hip under bar and weight on the heels. It is easier to go down if you raise your heel couple of inches (plates, plank).",
    Instruction3: "Keep chest up and head parallel to your spine. Pull the weight steadily up. In up-position check that your chest is open and shoulders are down and same line with your spine.  ",
    Instruction4: "Sit straight and take a wide grip. Rise your head and pull the shoulders down to activate back muscles. Pull the weight to your chin so that elbows come to the side of your body.  Throughout the exercise keep the shoulders down, so that movement circulates your shoulder joint.",
    Instruction5: "Sit in good posture. Keep the shoulders and lower back tight on the bench. Lowering the weight open your knees little bit and keep the weight on your heels all the time.",
    Instruction6: "In start position keep good posture with open chest. Bring your elbows a bit forward from the shoulder joint and start curling.",
    Instruction7: "***",
    Instruction8: "Lie on the bench and keep your hip fasten to the bench throughout movement. Keep also feet turned upwards. Curl the weight up to the point where you can still hold the hip on the bench.",
    Instruction9: "Sit in good posture and keep your feet upwards throughout the exercise.",
    Instruction10: "in the starting position hold the weight directly over your body. Start pressing the dumbbells upward from the ear level. Keep your elbows in the same line with body and weight.",
    Instruction11: "Keep good posture and start pressing so that bar is in chin level.",
    Instruction12: "In good posture keep your shoulders, elbows an arms same line with your spine. Arch your elbows little bit outward, but keep shoulders in right place. Lift the weight up so that elbows lead the movement.",
    Instruction13: "Set the bench to the 30 degree angle. Throughout exercise keep the weights over the chest, not over shoulders. ",
    Instruction14: "Doing the exercise  keep the dumbbels all the time over the lower part of your pectorals. Arch your arms and keep your hands and elbows in the same line.",
    Instruction15: "Lean little bit forward.",
    Instruction16: "***",
    Instruction17: "***",
    Instruction18: "***",
    Instruction19: "***",
    Instruction20: "***",
    Instruction21: "***",
    Instruction22: "***",
    Instruction23: "***",
    Instruction24: "***",
    Instruction25: "***",
    Instruction26: "***",
    Instruction27: "***",
    Instruction28: "***",
    Instruction29: "***",
    Instruction30: "***",

    Caution1: "Do not let your chest fall. Keep your shoulders in place and do not let them rotate front or up.",
    Caution2: "Do not let your upper body lean forward. Keep in mind to hold the weight on the heels not on the toes at any point.",
    Caution3: "Pulling and lowering the weight make sure that you keep the chest up and do not round your back.",
    Caution4: "Keep your chest up all the time and minimize the body movement backwards.",
    Caution5: "Do not let the weight go to your toes and go only so low that you can keep your lower back fasten to the bench. keep you knees in the same position all the time.",
    Caution6: "Keep elbows steady all the time. Do not let them move backwards or open outwards.",
    Caution7: "***",
    Caution8: "Do not lift your hip or lower the too low.",
    Caution9: "Do not straighten your feet or lean back upper body.",
    Caution10: "Do not let the dumbbells go frontside or you elbows go backwards. ",
    Caution11: "Do not lean your upper body back or go so long up that you lock elbows.",
    Caution12: "Keep the weight on the side and do not raise the elbows higher than shoulder joint.",
    Caution13: "During the rep keep the chest up an do not let the shoulders rotate up or front. Do not stretch too far down, because it easy to begin pressing with the shoulders.",
    Caution14: "Keep the good posture with shoulder blades back. Keep the stretching on the chest. Do not try to stretch shoulders.",
    Caution15: "***",
    Caution16: "***",
    Caution17: "***",
    Caution18: "***",
    Caution19: "***",
    Caution20: "***",
    Caution21: "***",
    Caution22: "***",
    Caution23: "***",
    Caution24: "***",
    Caution25: "***",
    Caution26: "***",
    Caution27: "***",
    Caution28: "***",
    Caution29: "***",
    Caution30: "***",

    Variation1: "Try different handles. Leaning back exercise affects upper back/trapezius muscles.",
    Variation2: "Try front squat to learn how to keep upper body in right position. ",
    Variation3: "Try different dephts with hip, Lower hip position you work more with glutes and thighs and higher position back.",
    Variation4: "If you lean back or let your elbows move bacwards exercise targets trapezius and upper back muscles.",
    Variation5: "Try different leg positions, but keep in mind that even with narrow positions, keep the weight on the heels and lower back fasten.",
    Variation6: "Try exercise with dumbbells and also with cable.",
    Variation7: "***",
    Variation8: "***",
    Variation9: "***",
    Variation10: "You can do the exercise in the machine.",
    Variation11: "***",
    Variation12: "***",
    Variation13: "***",
    Variation14: "***",
    Variation15: "***",
    Variation16: "***",
    Variation17: "***",
    Variation18: "***",
    Variation19: "***",
    Variation20: "***",
    Variation21: "***",
    Variation22: "***",
    Variation23: "***",
    Variation24: "***",
    Variation25: "***",
    Variation26: "***",
    Variation27: "***",
    Variation28: "***",
    Variation29: "***",
    Variation30: "***",
  };