export default {
    Home: 'Dashboard' ,
    Profile: 'Profile' ,
    LogIn: 'Log in',
    Register: "Register",
    LogInWithFacebook: "Log in with Facebook",
    LogInwithGoogle: "Log in with Google",
    ForgotYourPassword: "Forgot your password?",
    Doyouwanttostartrightnow:	"Do you want to start right now?",
    PopularPrograms:	"Popular Programs",
    Programs:	"Programs",
    ChooseProgram:	"Choose Program",
    BrowsePrograms:	"Browse Programs",
    SelectYourprogram:	"Choose own program",
    YourProgram: "Your Program",
    MakeOwnProgram:	"Create own program",
    Gender:	"Gender",
    Level:	"Level", 
    PerWeek:	"per week",
    focus:	"Focus",
    Diary:	"Diary",
    Weight:	"Weight",
    ownWeight: "Own Weight",
    TotalWeight:	"Total Weight",
    maxWeight: "Record Weight",
    AverageWeight:	"Average Weight",
    Set: "Set",
    Sets: "Sets",
    Reps: "Reps",
    Total: "Total",
    HowLong: "Duration",
    YouhaveworkoutToday: "You have workout today",
    YouHaveRestDay: "You have rest day",
    Advice: "Advice",
    Addworkout:	"Add workout",
    Addactivity:	"Add Activity",
    Exercises: 	"Exercises",
    Exercise: "Exercise",
    ExercisesThisWeek: "Exercises this week",
    ExercisesLibrary: "Exercises Library",
    SearchExercises: "Search Exercises",
    All: "All",
    totalDays: "Total Days",
    days: "Days",
    weeks: "Weeks",
    week: "Week",
    inWeek: "in week",
    muscles: "muscles",
    isolation:	"isolation",
    basic:	"basic",
    chest:	"Chest",
    back:	"Back",
    shoulders:	"Shoulders",
    biceps:	"Biceps",
    triceps:	"Triceps",
    abs:	"Abs",
    legs:	"Legs",
    glutes:	"Glutes",
    calves:	"Calves",
    Workouts: "Workouts",
    workoutsFinished:	"Workouts done",
    exersiscesFinished:	"Exercises finished",
    currentProgram:	"Current program",
    currentLevel:	"Current level",
    maximumWeight:	"Record weight",
    ViewStatistics:	"View statistics",
    AverageWorkoutTime:	"Average workout time",
    currentExercise:	"Current exercise",
    muscleGroup:	"Muscle group",
    upcomingExercise:	"Upcoming exercise",
    Previous: "Previous",
    NextWeek: "Next Week",
    Delete: "Delete",
    TotalExercises: "Total Exercises",
    Discover: "Discover",
    WePrepared: 'We prepared a programs that will fit your needs',
    DoneThisWeek: "Done this week",
    DoneThisDay: "Done this day",
    CustomExercises: "Custom exercise",
    ContinueProgram: "Continue program",
    NoData: "No Data Here",
    Logout: "Log out",
    ChangeWeight: "Change weight",
    LeaveProgram: "Leave program",
    LeaveProgramAlert: "You are about to end the program. Are you sure?",
    DiaryPromoTitle: "Record and track achievements",
    DiaryPromo: "A diary will show the statistics for each training day and will inform you about upcoming trainings",
    ExercisesPromoTitle: "Exercises Library",
    ExercisesPromoText: "Find the exercises according to the muscle groups and the type. Additionaly, we have videos, that will help you learn train effectively and safely",
    Cancel: "Cancel" ,
    Add: "Add",
    CheckOut: "Check Out",
    RandomAdvice: "Remember to stretch after the traing to keep muscles in a good shape",
    DailyAdvice: "Daily Advice",
    LoginPromo: "Learn how to train rationally with our library of exercises with explanatory videos.",
    Email: "Email",
    Password: "Password",
    EnterYourEmail: "Enter your email",
    EnterPassword: "Enter your password",
    EnterName: "Enter your name",
    Male: "Male",
    Female: "Female",
    male: 'male',
    female: 'female',
    both: 'both',
    exercisesDone: "Exercises done",
    TotalSets: "Total sets",
    TotalReps: "Toral reps",
    FeedbackText: "Ole hyvä ja arvioi treenin vaikeus, että voimme muokata ohjelmaa eteenpäin",
    Next: "Seuraava",
    Measurements: "Kirjaa mitat",
    HowManyWeeks: "Kuinka monta kertaa viikossa harjoittelet?",
    FillBasic: "Hienoa! Täytä perustiedot ja olet valmis aloittamaan",
    Done: "Tehty",
    Height: "Pituus",
    Name: "Käyttäjänimi",
    ExerciseName: "Harjoitusliike",
    EnterExerciseName: "Kirjoita liikkeen nimi",
    ProgramsPromo: "Kaikki ohjelmat ovat ammattilaisten suunnittelemia",
    First: "Ensimmäinen",
    Second: "Toinen",
    Third: "Kolmas",
    Fourth: "Neljäs",
    Fifth: "Viides",
    Sixth: "Kuudes",
    Seventh: "Seitsemäs",
    Day: "Päivä",
    WorkoutIsCompleted: "Harjoitus tehty!",
    Feedback: "Palaute",
    Bad: "Helppo",
    Fine: "Sopiva",
    VeryGood: "Vaikea",
    SelectWorkoutDays: "Valitse treenipäivät",
    ChooseAtWhatDays: "Merkkaa päivät milloin harjoittelet",
    Monday: "Maanantai",
    Tuesday: "Tiistai",
    Wednesday: "Keskiviikko",
    Thursday: "Torstai",
    Friday: "Perjantai",
    Saturday: "Lauantai",
    Sunday: "Sunnuntai",
    Save: "Tallenna",
    
  
  
    EnrollToProgram: "Valitse ohjelma",
    EditProgram: "Edit",
    DoneWorkoutToday: "Olet tehnyt harjoituksen tänään",
  
    //Exercises
    ExerciseName: "Liikkeen nimi",
    Benchpress:	"Penkkipunnerrus",
    Inclinedumbbellpress:	"Vinopenkkipunnerrus käsipainoilla",
    Lyingflyes: "Levitykset käsipainoilla",
    PecDekFlyes:	"Rintalevityslaite",
    Crossover:	"Ristitalja",
    Chins:	"Leuanveto",
    Latpulldown:	"Ylätalja",
    Seatedcablerow:	"Alatalja",
    x2:	"Ristitaljaveto",
    Alaspaino:	"Alaspaino taljassa",
    Deadlift:	"Maastaveto",
    BentoverRow:	"Kulmasoutu",
    ShoulderPress: "Pystypunnerrus",
    Uprightcablerow:	"Pystysoutu",
    Standingdumbbellfly:	"Vipunosto sivulle käsipainoilla",
    DumbbellBentOverLateralRaise:	"Vipunosto olkapään takaosalle",
    FrontDumbbellRaise:	"Vipunosto eteen käsipainoilla",
    BicepsCurl:	"Hauiskääntö",
    Concentrationcurl:	"Keskitetty yhden käden hauiskääntö",
    BenchDip:	"Penkkidippi",
    Tricepspushdown:	"Ojentajapunnerrus",
    Lyingtricepsextensions:	"Ojentajakääntö maaten taljassa",
      TricepsPushDownWithRope: "Ojentajapunnerrus taljassa",
    Crunch:	"Vatsarutistus maaten",
    LegRaises:	"Jalkojen nosto",
    ABCable:	"Vatsarutistus ristitaljassa",
    Squat:	"Jalkakyykky",
    HackSquat:	"Hack-kyykky",
    SquatSmith:	"Smith -kyykky",
    LegPress:	"Jalkaprässi",
    Legextensions:	"Etureisipenkki",
    SeatedLegCurl:	"Reidenkoukistus istuen",
    Lyinglegcurl:	"Takareisilaite",
    CableKickback:	"Pakarapotku taljassa",
    StiffLeggedBarbellDeadlift:	"Maastaveto suorin jaloin",
    GluteSquat:	"Jalkakyykky pakaralle",
    Lunges: "Askelkyykky",
    Standingcalfraise:	"Pohjelaite seisten",
    SeatedCalfRaise:	"Pohjelaite istuen",
    ClosedCableRow: "?",
    Legraiseonthebench: "Vatsarutistus istuen",
    others: 'muuta',
    all: 'Kaikki',
    ShowMore: "näytä lisää",
    Hide: "piilottaa"
  };