export default {
    Home: 'Dashboard' ,
    Profile: 'Profile' ,
    LogIn: 'Log in',
    Register: "Register",
    LogInWithFacebook: "Log in with Facebook",
    LogInwithGoogle: "Log in with Google",
    ForgotYourPassword: "Forgot your password?",
    Doyouwanttostartrightnow:	"Do you want to start right now?",
    PopularPrograms:	"Popular Programs",
    Programs:	"Programs",
    ChooseProgram:	"Choose Program",
    BrowsePrograms:	"Browse Programs",
    SelectYourprogram:	"Choose own program",
    YourProgram: "Your Program",
    MakeOwnProgram:	"Create own program",
    Gender:	"Gender",
    Level:	"Level", 
    PerWeek:	"per week",
    focus:	"Focus",
    Diary:	"Diary",
    Weight:	"Weight",
    ownWeight: "Own Weight",
    TotalWeight:	"Total Weight",
    maxWeight: "Record Weight",
    AverageWeight:	"Average Weight",
    Set: "Set",
    Sets: "Sets",
    Reps: "Reps",
    Total: "Total",
    HowLong: "Duration",
    YouhaveworkoutToday: "You have workout today",
    YouHaveRestDay: "You have rest day",
    Advice: "Advice",
    Addworkout:	"Add workout",
    Addactivity:	"Add Activity",
    Exercises: 	"Exercises",
    Exercise: "Exercise",
    ExercisesThisWeek: "Exercises this week",
    ExercisesLibrary: "Library",
    SearchExercises: "Search Exercises",
    All: "All",
    totalDays: "Total Days",
    days: "Days",
    weeks: "Weeks",
    week: "Week",
    inWeek: "in week",
    muscles: "muscles",
    isolation:	"isolation",
    basic:	"basic",
    chest:	"Chest",
    back:	"Back",
    shoulders:	"Shoulders",
    biceps:	"Biceps",
    triceps:	"Triceps",
    abs:	"Abs",
    legs:	"Legs",
    glutes:	"Glutes",
    calves:	"Calves",
    Workouts: "Workouts",
    workoutsFinished:	"Workouts done",
    exersiscesFinished:	"Exercises finished",
    currentProgram:	"Current program",
    currentLevel:	"Current level",
    maximumWeight:	"Record weight",
    ViewStatistics:	"View statistics",
    AverageWorkoutTime:	"Average workout time",
    currentExercise:	"Current exercise",
    muscleGroup:	"Muscle group",
    upcomingExercise:	"Upcoming exercise",
    Previous: "Previous",
    NextWeek: "Next Week",
    Delete: "Delete",
    TotalExercises: "Total Exercises",
    Discover: "Discover",
    WePrepared: 'We prepared a programs that will fit your needs',
    DoneThisWeek: "Done this week",
    DoneThisDay: "Done this day",
    CustomExercises: "Custom exercise",
    ContinueProgram: "Continue program",
    NoData: "No Data Here",
    Logout: "Log out",
    ChangeWeight: "Change weight",
    LeaveProgram: "Leave program",
    LeaveProgramAlert: "You are about to end the program. Are you sure?",
    DiaryPromoTitle: "Record and track achievements",
    DiaryPromo: "A diary will show the statistics for each training day and will inform you about upcoming trainings",
    ExercisesPromoTitle: "Exercises Library",
    ExercisesPromoText: "Find the exercises according to the muscle groups and the type. Additionaly, we have videos, that will help you learn train effectively and safely",
    Cancel: "Cancel" ,
    Add: "Add",
    CheckOut: "Check Out",
    RandomAdvice: "Remember to stretch after the traing to keep muscles in a good shape",
    DailyAdvice: "Daily Advice",
    LoginPromo: "Learn how to train rationally with our library of exercises with explanatory videos.",
    Email: "Email",
    Password: "Password",
    EnterYourEmail: "Enter your email",
    EnterPassword: "Enter your password",
    EnterName: "Enter your name",
    Male: "Male",
    Female: "Female",
    male: 'male',
    female: 'female',
    both: 'both',
    exercisesDone: "Exercises done",
    TotalSets: "Total sets",
    TotalReps: "Toral reps",
    FeedbackText: "Please evaluate the difficulty of the training so that we can adjust the program for you",
    Next: "Next",
    Measurements: "Enter your details",
    HowManyWeeks: "How many days per week you want to train?",
    FillBasic: "Great! Fill the basic information below and you are ready!",
    Done: "Done",
    Height: "Height",
    Name: "Name",
    ExerciseName: "Exercise name",
    EnterExerciseName: "Enter exercise name",
    ProgramsPromo: "All programs are designed by professionals",
    First: "First",
    Second: "Second",
    Third: "Third",
    Fourth: "Fourth",
    Fifth: "Fifth",
    Sixth: "Sixth",
    Seventh: "Seventh",
    Day: "Day",
    WorkoutIsCompleted: "Workout is completed!",
    Feedback: "Feedback",
    Bad: "Hard",
    Fine: "Perfect",
    VeryGood: "Easy",
    SelectWorkoutDays: "Select Workout Days",
    ChooseAtWhatDays: "Please mark the workout days",
    Monday: "Monday",
    Tuesday: "Tuesday",
    Wednesday: "Wednesday",
    Thursday: "Thursday",
    Friday: "Friday",
    Saturday: "Saturday",
    Sunday: "Sunday",
    Save: "Save",
    
  
    EnrollToProgram: "Enroll to program",
    EditProgram: "Edit",
    DoneWorkoutToday: "You have finished workout today",
  
    //Exercises
    ExerciseName: "Exercise name",
    Benchpress:	"Benchpress",
    Inclinedumbbellpress:	"Incline dumbbell press",
    Lyingflyes: "Lying chest fly",
    PecDekFlyes:	"Pec deck flyes",
    Crossover:	"Cable Crossover",
    Chins:	"Chin-Up",
    Latpulldown:	"Lat pull down",
    Seatedcablerow:	"Seated cable row",
    x2:	"Cross over pulley",
    Alaspaino:	"Standing cable pullover",
    Deadlift:	"Deadlift",
    BentoverRow:	"Bent over row",
    ShoulderPress: "Shoulder Press",
    Uprightcablerow:	"Upright cable row",
    Standingdumbbellfly:	"Standing dumbbell fly",
    DumbbellBentOverLateralRaise:	"Dumbbell bent-over raise",
    FrontDumbbellRaise:	"Front dumbbell raise",
    BicepsCurl:	"Biceps curl",
    Concentrationcurl:	"Concentration curl",
    BenchDip:	"Bench dip",
    Tricepspushdown:	"Triceps pushdown",
    Lyingtricepsextensions:	"Lying triceps extensions",
    TricepsPushDownWithRope: "Triceps pushdown (with rope)",
    Crunch:	"Crunch",
    LegRaises:	"Leg raises",
    ABCable:	"Ab Pulldown",
    Squat:	"Squat",
    HackSquat:	"Hack squat",
    SquatSmith:	"Squat smith machine",
    LegPress:	"Leg press",
    Legextensions:	"Leg extensions",
    SeatedLegCurl:	"Seated leg curl",
    Lyinglegcurl:	"Lying leg curl",
    CableKickback:	"Cable kickbacks",
    StiffLeggedBarbellDeadlift:	"Stiff-legged barbell deadlift",
    GluteSquat:	"Glute squat",
    Lunges: "Lunges",
    Standingcalfraise:	"Standing calf raise",
    SeatedCalfRaise:	"Seated calf raise",
    ClosedCableRow: "Closed cable row",
    Legraiseonthebench: "Leg raise on the bench",
    others: 'others',
    all: 'all',
    ShowMore: "Show more",
    Hide: "Hide"
  };