export default {
  Home: 'Kotisivu' ,
  Profile: 'Profiili' ,
  LogIn: 'Kirjaudu sisään',
  Register: "Rekisteröidy",
  LogInWithFacebook: "Kirjaudu Facebook tunnuksilla",
  LogInwithGoogle:	"Kirjaudu Google tunnuksilla",
  ForgotYourPassword: "Unohditko salasanasi?",
  Doyouwanttostartrightnow:	"Haluatko aloittaa heti?",
  PopularPrograms:	"Suositut ohjelmat",
  Programs:	"Ohjelmat",
  ChooseProgram:	"Valitse ohjelma",
  BrowsePrograms:	"Selaa ohjelmia",
  SelectYourprogram:	"Valitse oma ohjelma",
  YourProgram: "Oma Ohjelma",
  MakeOwnProgram:	"Tee oma ohjelma",
  Gender:	"Sukupuoli",
  Level:	"Taso", 
  PerWeek:	"kertaa viikossa",
  focus:	"Tavoite",
  Diary:	"Päiväkirja",
  Weight:	"Paino",
  ownWeight: "Oma Paino",
  TotalWeight:	"Kiloja yhteensä",
  maxWeight: "Suurin paino",
  AverageWeight:	"Keskiarvopaino",
  Set: "Sarja",
  Sets:	"Sarjat",
  Reps: "Toistot",
  Total: "Yhteensä",
  HowLong: "Kesto",
  YouhaveworkoutToday:	"Sinulla on harjoitus tänään",
  YouHaveRestDay: "Sinulla on lepopäivä tänään",
  Advice: "ohje",
  Addworkout:	"Lisää harjoitus",
  Addactivity:	"Lisää aktiviteetti",
  Exercises: 	"Liikkeet",
  Exercise: "Liike",
  ExercisesThisWeek: "Viikon Liikkeet",
  ExercisesLibrary:	"Liikekirjasto",
  SearchExercises:	"Etsi liike",
  All: "Kaikki",
  totalDays: "Yhteensä päiviä",
  days: "päiviä",
  weeks: "viikkoa",
  week: "Vikko",
  inWeek: "Viikon",
  muscles: "lihakset",
  isolation:	"Eristävä",
  basic:	"Perus",
  chest:	"Rinta",
  back:	"Selkä",
  shoulders:	"Olkapäät",
  biceps:	"Hauis",
  triceps:	"Ojentajat",
  abs:	"Vatsa",
  legs:	"Jalat",
  glutes:	"Pakarat",
  calves:	"Pohkeet",
  Workouts: "Treenit",
  Workout: "Treenit",
  workoutsFinished:	"Tehdyt treenit",
  exersiscesFinished:	"Tehdyt liikkeet",
  currentProgram:	"Nykyinen ohjelma",
  currentLevel:	"Nykyinen taso",
  maximumWeight:	"Maksimipaino",
  ViewStatistics:	"Näytä statistiikka",
  Statistics: 'statistiikka',
  AverageWorkoutTime:	"Keskiarvo harjoitus aika",
  currentExercise:	"Nykyinen liike",
  muscleGroup:	"Lihasryhmä",
  upcomingExercise:	"Tuleva liike",
  Previous: "Edellinen",
  NextWeek: "Seuraava Viikko",
  Delete: "Poistaa",
  TotalExercises: "Kokonais Liike",
  Discover: "Kokeile",
  WePrepared: 'Valitse sinun tavoitteisiin ja tarpeisiin sopiva ohjelma',
  DoneThisWeek: "Viikon harjoitukset",
  DoneThisDay: "Päivän harjoitukset",
  CustomExercises: "Oma Liike",
  ContinueProgram: "Jatka ohjelmaa",
  Continue: 'Jatka',
  NoData: "No Data Here",
  Logout: "Kirjaudu ulos",
  ChangeWeight: "Vaihda",
  LeaveProgram: "Poistu ohjelmasta",
  LeaveProgramAlert: "Olet lopettamassa ohjelmaa. Oletko varma?",
  DiaryPromoTitle: "Kirjaa ja seuraa kehitystä",
  DiaryPromo: "Treenipäiväkirja ja tulokset joka päivältä, viikko viikolta. Lisää omia huomioita ja kirjaa myös aerobinen harjoittelu",
  ExercisesPromoTitle: "Liikekirjasto",
  ExercisesPromoText: "Löydä liikkeet lihasryhmien ja liikejaottelun mukaisesti. Videoiden avulla opit tehokkaat ja turvalliset tavat harjoitella",
  Cancel: "Peruuta" ,
  Add: "Lisää",
  CheckOut: "Katso",
  RandomAdvice: "Muista venytellä. Halvin tapa huoltaa lihaksia!",
  DailyAdvice: "Päivän vinkki",
  LoginPromo: "Opi käyttämään kehoa ja lihaksiasi. Videoiden avulla opit harjoittamaan lihaksiasi, etkä rasita niveliä.",
  Email: "Sähköposti",
  Password: "Salasana",
  EnterYourEmail: "Kirjoita sähköposti",
  EnterPassword: "Kirjoita Salasana",
  EnterName: "Kirjoita nimesi",
  Male: "Mies",
  Female: "Nainen",
  male: 'Mies',
  female: 'Nainen',
  both: '',
  exercisesDone: "Treeniliikkeitä",
  TotalSets: "Sarjoja yhteensä",
  TotalReps: "Toistoja yhteensä",
  FeedbackText: "Ole hyvä ja arvioi treenin vaikeus, että voimme muokata ohjelmaa eteenpäin",
  Next: "Seuraava",
  Measurements: "Kirjaa mitat",
  HowManyWeeks: "Kuinka monta kertaa viikossa harjoittelet?",
  FillBasic: "Hienoa! Täytä perustiedot ja olet valmis aloittamaan",
  Done: "Tehty",
  Height: "Pituus",
  Name: "Käyttäjänimi",
  ExerciseName: "Harjoitusliike",
  EnterExerciseName: "Kirjoita liikkeen nimi",
  ProgramsPromo: "Kaikki ohjelmat ovat ammattilaisten suunnittelemia",
  First: "Ensimmäinen",
  Second: "Toinen",
  Third: "Kolmas",
  Fourth: "Neljäs",
  Fifth: "Viides",
  Sixth: "Kuudes",
  Seventh: "Seitsemäs",
  Day: "Päivä",
  WorkoutIsCompleted: "Harjoitus tehty!",
  Feedback: "Palaute",
  Bad: "Helppo",
  Fine: "Sopiva",
  VeryGood: "Vaikea",
  SelectWorkoutDays: "Valitse treenipäivät",
  ChooseAtWhatDays: "Merkkaa päivät milloin harjoittelet",
  Monday: "Maanantai",
  Tuesday: "Tiistai",
  Wednesday: "Keskiviikko",
  Thursday: "Torstai",
  Friday: "Perjantai",
  Saturday: "Lauantai",
  Sunday: "Sunnuntai",
  Save: "Tallenna",
  EnrollToProgram: "Valitse ohjelma",
  EditProgram: "Muokka Ohjelmaa",
  DoneWorkoutToday: "Olet tehnyt harjoituksen tänään",
  Edit: 'Muokka',
  //Exercises
  ExerciseName: "Liikkeen nimi",
  

  SeatedCableRow:	"Alatalja",
  Squats: "Kyykky tanko",
  DeadLift:	"Maastaveto",
  LatPulldown:	"Ylätalja",
  LegPress:	"Jalkaprässi",
  BicepsCurl:	"Hauiskääntö",
  SmithMachineSquat: "Kyykky smith",
  LegCurls: "Koukistus maaten",
  LegExtension:	"Reidenojennus",
  DumbbellShoulderPress: "Pystypunnerrus käsipainoin",
  MilitaryPress: "Pystypunnerrus",
  SideLaterals: "Vipunosto sivulle käsipainoilla",
  InclineDumbbellPress:	"Vinopenkkipunnerrus käsipainoilla",
  DumbbellFly: "Levitykset käsipainoilla",
  CablePushdown: "Ojentajakääntö taljassa",
  RearLaterals: "Takaolkapää käsipainoin",
  FlyesMachine: "Flyeslaite",
  BenchPress:	"Penkkipunnerrus",
  FrenchCurls: "Ranskalainen maaten talja",
  BentoverRow:	"Kulmasoutu",
  CableCrunch: "Rutistus taljassa",
  ConcentrationCurl:	"Keskitetty käsipaino",
  Crunches:	"Rutistus maaten",
  LegRaises:	"Jalkojen nosto penkilla",
  DeadliftGlutes: "Maastaveto pakara",
  Abduction: "Loitonnus",
  Lunges: "Askelkyykky",
  StandingCalfRaise:	"Pohjelaite seisten",
  SeatedCalfRaise:	"Istuen laite",
  GluteSquats:	"Pakarakyykky",
  Loading: 'Ladataan',

  // Lyingflyes: "Levitykset käsipainoilla",
  // PecDekFlyes:	"Rintalevityslaite",
  // Crossover:	"Ristitalja",
  // Chins:	"Leuanveto",
  // x2:	"Ristitaljaveto",
  // Alaspaino:	"Alaspaino taljassa",
  // ShoulderPress: "Pystypunnerrus",
  // Uprightcablerow:	"Pystysoutu",
  // Standingdumbbellfly:	"Vipunosto sivulle käsipainoilla",
  // DumbbellBentOverLateralRaise:	"Vipunosto olkapään takaosalle",
  // FrontDumbbellRaise:	"Vipunosto eteen käsipainoilla",
  // Concentrationcurl:	"Keskitetty yhden käden hauiskääntö",
  // BenchDip:	"Penkkidippi",
  // Tricepspushdown:	"Ojentajapunnerrus",
  // Lyingtricepsextensions:	"Ojentajakääntö maaten taljassa",
	// TricepsPushDownWithRope: "Ojentajapunnerrus taljassa",
  // LegRaises:	"Jalkojen nosto",
  // ABCable:	"Vatsarutistus ristitaljassa",
  // Squat:	"Jalkakyykky",
  // HackSquat:	"Hack-kyykky",
  // SquatSmith:	"Smith-kyykky",
  // Legextensions:	"Etureisipenkki",
  // SeatedLegCurl:	"Reidenkoukistus istuen",
  // Lyinglegcurl:	"Takareisilaite",
  // CableKickback:	"Pakarapotku taljassa",
  // StiffLeggedBarbellDeadlift:	"Maastaveto suorin jaloin",
  // GluteSquats:	"Jalkakyykky pakaralle",
  // SeatedCalfRaise:	"Pohjelaite istuen",
  // Legraiseonthebench: "Vatsarutistus istuen",

  // End of Exercises
  others: 'muuta',
  all: 'Kaikki',
  ShowMore: "näytä lisää",
  Hide: "piilottaa",
  CreateYourOwn: 'Luo oma ohjelma',
  AllPrograms: 'Kaikki ohjelmat',
  GoPremium: 'Hanki Premium',
  
  PayWithCard: 'Maksaa kortilla',
  Pay: 'Maksaa',
  Replace: 'Korvaa',
  WithOneFromBelow: 'Yksi alla olevasta',
  SameExerciseExists: 'Sama harjoitus on olemassa',
  Instructions: "Ohjeet",
  Cautions: "Varoitukset",
  Variations: "Muunnelmat",

  // NEW
  ManageExercises: 'MANAGE EXERCISES',
  ManageExercisesPromo: 'Manage exercises promo',
  PremiumPromo: 'Käytä hyödyksi liikekirjastoa ja harjoituspäiväkirjaa tehostamaan harjoittelua',
  ChangeWorkoutDays: 'Vaihda harjoituspäivien järjestystä',
  NoEquipment: 'Ei laitetta?',
  ReplaceWithAlternative: 'Korvaa vaihtoehtoisella liikkeellä',
  ChargeSubscription: 'Veloitus RationalGym Premium tilauksesta',
  ContactInfo: 'Ole hyvä ja ota yhteyttä info@rational-gym.com, jos sinulla on kysyttävää maksusta',
  SaveAndReturn: 'Tallenna ja palaa edelliseen',
  BestMatchProgram: 'Suositeltu ohjelma',
  ScheduleSaved: 'Suunnitelma on tallennettu. Voit vaihtaa päiviä myöhemmin asetuksista.',
  OwnProgramInstruction: 'Täytä perustiedot ohjelmastasi. Voit järjestää lihasryhmät uudestaan päivien mukaisesti myöhemmin.',
  YourProgress: 'Sinun edistyminen',
  EditingPrograms: 'Muokkaa ohjelmaa',
  QuickWorkoutButton: 'Pikatreeni nappi',
  QuickWorkout: 'Pikatreeni',
  ExerciseVideos: 'Liikevideot',
  BeginWorkout: 'Aloita harjoitus',
  MoreThan4Weeks: 'Olet harjoitellut yli 4 viikkoa. Hienoa työtä!',
  WhatDoYouWantToTrain: 'Mitä lihasryhmiä haluat harjoitella?',
  UseTheSlider: 'Nuolella voit liikkua päivien välillä ja järjestää harjoitukset lihasryhmittäin.',


    //Programs
    P1JakoinenTaso1: '1-Jakoinen Taso 1',
    P1JakoinenTaso2: '1-Jakoinen Taso 2',
    P1JakoinenTaso3: '1-Jakoinen Taso 3',
    P2JakoinenTaso1: '2-Jakoinen Taso 1',
    P2JakoinenTaso2: '2-Jakoinen Taso 2',
    P3JakoinenTaso1: '3-Jakoinen Taso 1',
    P4JakoinenTaso1: '4-Jakoinen Taso 1',
    P4JakoinenTaso2: '4-Jakoinen Taso 2',




      // Instructions, Cautions and Variations
      Instruction1: "Istu ryhdikkäästi liikkeen aikana ja vedä tanko vatsan keskiosan kohdalle. Pidä kyynärpäät auki kyljistä ja rintakehä ylhäällä koko liikkeen ajan.",
      Instruction2: "Seiso suorassa ja pidä lantio keskivartalon avulla hyvässä asennossa. Mene kyykkyyn niin, että selkä ja lantio ovat tangon alla koko liikkeen ajan.",
      Instruction3: "Pidä rintakehä ylhäällä ja aktivoi selän lihakset. Nosta lantiota ylöspäin, mutta pidä rintakehän ja olkapäiden asento samana ja pään asento selkärangan suuntaisena. Vedä paino tasaisesti ylös. Yläasennossa tarkista, että olkapäät ovat alhaalla ja rintakehä on auki. Näin tunnet selkälihakset. ",
      Instruction4: "Istu suorassa ja pidä tangosta kiinni leveällä otteella. Vedä olkapäät alas ja nosta katse ylös. Vedä tanko leuan korkeudella niin, että kyynärpäät tulevat alas kehon suuntaisesti. ",
      Instruction5: "Istu ryhdikkäästi. Pidä hartiat ja alaselkä kiinni penkissä. Tee liike tasaisesti niin, että varsinkin pohja-asennossa tunnet painon kantapäillä. Tee liike ainoastaan niin syvään, ettei alaselkä irtoa penkistä",
      Instruction6: "Seiso hyvässä ryhdissä ja pidä olkapäillä rintakehä auki. Tuo kyynärpää hieman olkanivelen etupuolelle ja aloita koukistus.",
      Instruction7: "Tuo jalat tangon etupuolelle sen verran, että pohjassa (90 asteen säärikulma) selkä ja lantio ovat tangon alla/kohdalla ja paino on kantapäällä.",
      Instruction8: "Koukista jalkaterä ylöspäin ja koukista jalat painoa vasten n 90 asteen säärikulmaan. Venytysvaiheessa päästä paino vain niin alas, että tunnet edelleen lihaksen",
      Instruction9: "Istu ryhdikkäästi ja koukista varpaat nilkasta lähtien ylöspäin. Jännitä reisilihakset ja ojenna paino ylös.",
      Instruction10: "Alkuasennossa kämmenet ovat suunnilleen korvien korkeudella ja paino on kehon päällä. Kyynärpäät painon alla kehon suuntaisesti. Punnerra painot ylös suoralla liikeradalla. ",
      Instruction11: "Nosta paino rinnalta leuan tasolle ja punnerra paino suoraan ylös lukitsematta käsiä ylhäällä",
      Instruction12: "Pidä ylävartalon hyvä ryhti. Avaa kyynärpäitä hieman ulospäin, mutta pidä paino vartalon sivun myötäiseti. Ohjaa nostoa kyynärpää liikettä vieden.",
      Instruction13: "Kuten penkkipunnerrus, muuta säädä penkki noin 30 asteen kulmaan. Kun pidät kädet aloituksessa lukkosuorassa voit tarkistaa, että rintakehä on ylhäällä ja olkapäät alhaalla/takana. Siirrä paino rintalihaksen alaosan kohdalle ja tuo paino hallitusti alas.",
      Instruction14: "Alkuasento sama kuin punnerruksissa. Liikkeen aikana kämmenet vastakkain. Tee liike puolipyöreällä liikkeellä niin, että käsipainon, käden ja kyynärpään muodostama kaari on koko ajan rintalihaksen päällä.",
      Instruction15: "Nojaa hieman eteenpäin. Alkuasennossa eli n 90 asteen käsivarsi kulmassa kyynärpää on olkaniveltä edempänä. Liike rullaa kyynärpään yli.",
      Instruction16: "Nojaa jalkojen päälle ja laske kädet suoraan alas. Vedä lavat kiinni kädet suorina. Vedä paino ylös niin, että lavat pysyvät kiinni ja pystyt pitämään kyynärpäät hartialinjan suuntaisesti. Hae jännitys olkapään takaosaan. Pidä liike lyhyenä. ",
      Instruction17: "Nosta penkki niin ylös että käsien muodostama kaari on rintalihaksen alaosan kohdalla. Jännitä rintalihaksia liikkeen aikana liioittelemalla ja pidä samalla olkapäät mahdollisimman rentoina.",
      Instruction18: "Alkuasennossa rintakehä on ylhäällä ja olkapäät alhaalla/takana. Tuo tanko hallitusti kyynärpäät auki rintalihaksen alaosaan. Punnerra paino suoraan ylös niin, että tanko pysyy koko ajan rintalihaksen kohdalla",
      Instruction19: "Maatessasi penkillä siirrä kyynärpäätä pään suuntaan ja lukitse se. Liike pyörii kyynärnivelen ympäri ja voit ojentaa käyden täysin suoraksi.",
      Instruction20: "Ala-asennossa pidä yläkehon ryhti ja keskivartalo tiukkana. Vedä painoa ylös kyynärpäät auki (n. 45 asteen kulmassa kylkiin).Pidä pään asento selkärangan suuntaisena ja tee työ selä lihaksilla.",
      Instruction21: "Liikkeen ajan pidä lantio korkealla ja paikoillaan. Pidä köydestä kiinni kädet pään yläpuolella ja rutista keskivartalolla kyynärpäät polviin. Harjoittele niin, että kaikki liike on keskivartalossa. ",
      Instruction22: "Tue kyynärpää reittä vasten niin, että kyynärpää on edempänä olkapäätä. Keskity jännitämään hauista vastusta vasten.",
      Instruction23: "Makaa lattialla jalat penkillä reiden ja säären ollessa 90 asteen kulmassa. Nosta päätäsi, että saat leuan kohti rintaa ja vedä alavatsaa hieman sisään. Rutista vatsaa lattian suuntaisesti. Pidä pää koko ajan samassa asennossa.",
      Instruction24: "Tee liike vetämällä polvia rintaa kohti. Harjoittele samalla vatsan vakuumipitoa eli vedä alavatsaa sisäänpäin ja kanna yläkehoa korkealla.",
      Instruction25: "Maastavedon variaatio, missä liike suunnataan pakaralle ja reiden koukistajalle. Pidä jalat suorassa tai hieman koukussa, mutta muista ylävartalon ryhti ja keskivartalon pito. Tuo paino hallitusti reilusti polven alapuolelle niin, että tunnet venytyksen pakarassa ja reidenkoukistajassa. Vedä painoa ylöspäin pakaraa jännittäen.",
      Instruction26: "Nojaa liikkeessä reilusti eteenpäin. Avaa jalat ja etsi jännitys pakaraan. Tee liike niin, että tunnet koko ajan jännittäväsi pakaraa vastusta vasten. ",
      Instruction27: "Nojaa etuvartalon reilusti eteenpäin ja keskity pohjassa jännittämään pakaraa. Etsi liikealue, missä ainoastaan pakara työskentelee.",
      Instruction28: "Seiso laitteessa paino päkiällä ja pidä jalkapohja normaalissa asennossa. Nouse niin ylös kuin pohkeen varassa pääset.",
      Instruction29: "Kuten seisten liike",
      Instruction30: "Pidä keskivartalo kontrolissa ja hae pakaran jännitys syvältä. Tee liike syvällä ja keskity puristamaan pakaraa yhteen.",
  
      Caution1: "Pidä yläkeho stabiilina. Älä päästä rintakehää tai kyynärpäitä laskemaan liian alas.",
      Caution2: "Paino ei saa mennä varpaille, vaan se on pidettävä kantapäillä. Selkä ei saa pyöristyä, eikä rintakehä luhistua.",
      Caution3: "Selkä ei saa pyöristyä.",
      Caution4: "Rintakehä ei saa luhistua.",
      Caution5: "Älä irroita päätä nojasta. Yläasennossa ei kannata työntää jalkoja lukkosuoraan. ",
      Caution6: "Kyynärpää ei liiku liikkeen aikana taaksepäin, eikä aukea ulospäin. ",
      Caution7: "Yläkehon ryhti ei saa pettää, eikä lantio kiertyä tangon etu- tai takapuolelle, jolloin paino katoaa kantapäältä.",
      Caution8: "Älä nosta lantiota,",
      Caution9: "Jalkaterää ei kannata ojentaa suoraksi, koska painon kanto tulee tällöin polviniveleen. ",
      Caution10: "Paino ei saa karata kehon etupuolelle, eikä kyynärpäät kehon takapuolelle. Painoa ei myöskään kannata nostaa liian ylös, jolloin harjoitus karkaa olkapäiltä ojentajille.",
      Caution11: "Pidä ryhti hyvänä koko liikkeen ajan. Varo nojaamasta taaksepäin.",
      Caution12: "Painoa ei pidä päästää sivulinjan eteen eikä taakse, koska tällöin epäkäs aktivoituu. Loppuasennossa ranne on oltava kyynärpäätä alempana, eikä paino nouse olkaniveltä korkeammalle.",
      Caution13: "Olkapäät eivät saa liikkeen aikana kiertyä eteen- tai ylöspäin, koska silloin olkapäät ottavat painon vastaan.",
      Caution14: "Venytä ainoastaan niin pitkälle, että tunnet rinna, mutta venytys ei mene olkapäihin asti.",
      Caution15: "Kyynärpää ei saa liikkua liikkeen aikana.",
      Caution16: "Älä päästä lapoja auki liikkeen aikana, koska tällöin epäkäs suorittaa ison osan työstä. Älä myöskään anna kyynärpäiden vajota noston aikana kohti kylkiä.",
      Caution17: "Venytysvaiheessa tunne rintalihaksen liike, mutta älä venytä liian pitkälle taakse. ",
      Caution18: "Rintakehä ei saa laskea likkeen aikana, eikä olkapäät kieetyä eteen tai ylös. Painon on kuljettava rintalihakse, ei olkanivelen päällä, koko matkan.",
      Caution19: "Keskity tekemään liike vain ojentajilla. Älä vauhdita liikettä olkapäillä ja muista pitää kyynärpää paikoillaan.",
      Caution20: "Selkä ei saa pyöristyä. Vältä olkapäiden nousemista tai kiertymistä eteen, jolloin rintakehän asento romahtaa.",
      Caution21: "Varo lantion tippumista ja vältä vetämästä painoa hartioilla ja käsillä. ",
      Caution22: "Pidä kyynärpää paikoillaan ja ranne suorassa tai hieman ulospäin käännettynä liikkeen aikana. Pidä olkapää rentona. ",
      Caution23: "Pidä niska rentona ja kaikki liike keskivartalossa. Yritä pitää liike vaakasuuntaisena, ei nostavana.",
      Caution24: "Älä jännitä hartioita ja pidä liike keskivartalossa.",
      Caution25: "Tuo painoa ainoastaan niin ylös, että tunnet pakaran. Tullessasi liian ylös tai kadottaessai pakaran hallinnan saattaa alaselkä rasittua.",
      Caution26: "Pidä venytys lyhyenä ja kontrolloitun. Keskity jännittämään pakaraa. Älä vauhdita liikettä jaloilla.",
      Caution27: "***",
      Caution28: "On tärkeämpää kuinka ylös nouset, eikä se kuinka syvältä lähdet. ",
      Caution29: "Aloita liike jalkaterä vaakatasossa ja liikuta painoa pohkeella, ei nilkalla.",
      Caution30: "Mitä ylemmäs nouset, sitä helpommalla pakara pääsee.",
  
      Variation1: "Kokeile erilaisia kahvoja. Nojatessa taaksepäin saat liikkeen tuntumaan selän yläosan lihaksissa ja hartian takaosan lihaksissa.",
      Variation2: "Voit tehdä liikkeen etukyykkynä, jolloin yläkehon pito on helpompi oppia. Kokeile eri korkuisia korokkeita kantapään alle.",
      Variation3: "Kokeile liikkeen eri syvyyksiä. Polvesta alaspäin ja lantion ollessa alhaalla liike on alakehon harjoitusta ja polvesta ylöspäin yläkehon.",
      Variation4: "Kokeile erilaisia kahvoja. Nojatessa taaksepäin tai kyynärpäiden kiertyessä taaksepäin liike suuntautuu yläselän ja hartian lihaksiin.",
      Variation5: "Vaihda jalkaasentoja, mutta muista kiertää polvea hieman auki. Näin aktivoit reiden lihakset, eikä polvinivel kanna painoa.",
      Variation6: "Kokeile liikettä käsipainoilla ja taljassa.",
      Variation7: "Liikettä voi tehdä erilaisilla jalkaleveyksillä. ",
      Variation8: "***",
      Variation9: "***",
      Variation10: "Liikkeen voi tehdä laitteessa, tangolla jne.",
      Variation11: "***",
      Variation12: "***",
      Variation13: "Kokeile liikettä tangolla tai smith -laitteessa.",
      Variation14: "***",
      Variation15: "***",
      Variation16: "Avaamalla lavat liikkeen aikan saat liikkeen osumaan yläselkään.",
      Variation17: "***",
      Variation18: "***",
      Variation19: "***",
      Variation20: "Vaihtamalla ylävartalon kulmaa liike kohdistuu selän eri kohtiin. Nousemalla ylöspäin 90 asteen kulmasta liike ottaa enemmän uläselän lihaksiin.",
      Variation21: "***",
      Variation22: "Kokeile liikettä seisten, taljassa tai scott -penkissä. Vaihda käden suuntaa laitteen mukaan ja kohdista liikettä eri tavoin.",
      Variation23: "Voit pitää käsiä rinnan päällä tai niskan takana. Kokeile liikettä myös kiertona.",
      Variation24: "***",
      Variation25: "***",
      Variation26: "***",
      Variation27: "***",
      Variation28: "Vaihda jalkaterien asentoa ja tunne miten liike kohdistuu pohkeen eri osiin.",
      Variation29: "***",
      Variation30: "***",
};