export default {
  Home: 'Kotisivu' ,
  Profile: 'Profiili' ,
  LogIn: 'Kirjaudu sisään',
  Register: "Rekisteröidy",
  LogInWithFacebook: "Kirjaudu Facebook tunnuksilla",
  LogInwithGoogle:	"Kirjaudu Google tunnuksilla",
  ForgotYourPassword: "Unohditko salasanasi?",
  Doyouwanttostartrightnow:	"Haluatko aloittaa heti?",
  PopularPrograms:	"Suositut ohjelmat",
  Programs:	"Ohjelmat",
  ChooseProgram:	"Valitse ohjelma",
  BrowsePrograms:	"Selaa ohjelmia",
  SelectYourprogram:	"Valitse oma ohjelma",
  YourProgram: "Oma Ohjelma",
  MakeOwnProgram:	"Tee oma ohjelma",
  Gender:	"Sukupuoli",
  Level:	"Taso", 
  PerWeek:	"kertaa viikossa",
  focus:	"Tavoite",
  Diary:	"Päiväkirja",
  Weight:	"Paino",
  ownWeight: "Oma Paino",
  TotalWeight:	"Kokonaispaino",
  maxWeight: "Suurin paino",
  AverageWeight:	"Keskiarvopaino",
  Sets:	"Sarjat",
  Reps: "Toistot",
  Total: "Yhteensä",
  HowLong: "Kesto",
  YouhaveworkoutToday:	"Sinulla on harjoitus tänään",
  YouHaveRestDay: "Sinulla on lepopäivä tänään",
  Advice: "ohje",
  Addworkout:	"Lisää harjoitus",
  Addactivity:	"Lisää aktiviteetti",
  Exercises: 	"Liikkeet",
  Exercise: "Liike",
  ExercisesThisWeek: "Viikon Liikkeet",
  ExercisesLibrary:	"Liikekirjasto",
  SearchExercises:	"Etsi liike",
  All: "Kaikki",
  totalDays: "Yhteensä päiviä",
  days: "päiviä",
  weeks: "viikkoa",
  week: "Vikko",
  muscles: "lihakset",
  isolation:	"Eristävä",
  basic:	"Perus",
  chest:	"Rinta",
  back:	"Selkä",
  shoulders:	"Olkapäät",
  biceps:	"Hauis",
  triceps:	"Ojentajat",
  abs:	"Vatsa",
  legs:	"Jalat",
  glutes:	"Pakarat",
  calves:	"Pohkeet",
  Workouts: "Treenit",
  workoutsFinished:	"Tehdyt treenit",
  exersiscesFinished:	"Tehdyt liikkeet",
  currentProgram:	"Nykyinen ohjelma",
  currentLevel:	"Nykyinen taso",
  maximumWeight:	"Maksimipaino",
  ViewStatistics:	"Näytä statistiikka",
  AverageWorkoutTime:	"Keskiarvo harjoitus aika",
  currentExercise:	"Nykyinen liike",
  muscleGroup:	"Lihasryhmä",
  upcomingExercise:	"Tuleva liike",
  Previous: "Edellinen",
  NextWeek: "Seuraava Vikko",
  Delete: "Poistaa",
  TotalExercises: "Kokonais Liike",
  Discover: "Kokeile",
  WePrepared: 'Valitse sinun tavoitteisiin ja tarpeisiin sopiva ohjelma',
  DoneThisWeek: "Viikon harjoitukset",
  DoneThisDay: "Päivän harjoitukset",
  CustomExercises: "Oma Liike",
  ContinueProgram: "Jatka ohjelmaa",
  NoData: "No Data Here",
  Logout: "Kirjaudu ulos",
  ChangeWeight: "Vaihda",
  LeaveProgram: "Poistu ohjelmasta",
  LeaveProgramAlert: "Olet lopettamassa ohjelmaa. Oletko varma?",
  DiaryPromoTitle: "Kirjaa ja seuraa kehitystä",
  DiaryPromo: "Treenipäiväkirja ja tulokset joka päivältä, viikko viikolta. Lisää omia huomioita ja kirjaa myös aerobinen harjoittelu",
  ExercisesPromoTitle: "Liikekirjasto",
  ExercisesPromoText: "Löydä liikkeet lihasryhmien ja liikejaottelun mukaisesti. Videoiden avulla opit tehokkaat ja turvalliset tavat harjoitella",
  Cancel: "Peruuta" ,
  Add: "Lisää",
  CheckOut: "Katso",
  RandomAdvice: "Muista venytellä. Halvin tapa huoltaa lihaksia!",
  DailyAdvice: "Päivän vinkki",
  LoginPromo: "Opi käyttämään kehoa ja lihaksiasi. Videoiden avulla opit harjoittamaan lihaksiasi, etkä rasita niveliä.",
  Email: "sähköposti",
  Password: "Salasana",
  EnterYourEmail: "Kirjoita sähköposti",
  EnterPassword: "Kirjoita Salasana",
  EnterName: "Kirjoita nimesi",
  EnterExerciseName: "Kirjoita nimi",
  Male: "Mies",
  Female: "Nainen",
  male: 'Mies',
  female: 'Nainen',
  both: '',

  Next: "Seuraava",
  Measurements: "Kirjoita painosi",
  HowManyWeeks: "Kuinka monta kertaa viikossa haluat harjoitella?",
  FillBasic: "Hienoa! Täytä perustiedot ja olet valmis aloittamaan",
  Done: "Tehty",
  Height: "Korkeus",
  Name: "Nimesi",
  ProgramsPromo: "Kaikki ohjelmat ovat ammattilaisten suunnittelemia",
  First: "Ensimmäinen",
  Second: "Toinen",
  Third: "Kolmas",
  Fourth: "Neljäs",
  Fifth: "Viides",
  Sixth: "Kuudes",
  Seventh: "Seitsemäs",
  Day: "Päivä",

  EnrollToProgram: "Valitse ohjelma",
  EditProgram: "Edit",
  DoneWorkoutToday: "Olet tehnyt harjoituksen tänään",

  //Exercises
  ExerciseName: "Liikkeen nimi",
  BarbellBenchPress:	"Penkkipunnerrus",
  InclineBenchDumbbellPress:	"Vinopenkkipunnerrus käsipainoilla",
  Flyes: "Levitykset käsipainoilla",
  PecDekFlyes:	"Rintalevityslaite",
  Crossover:	"Ristitalja",
  Chins:	"Leuanveto",
  LatPullDown:	"Ylätalja",
  SeatedCableRow:	"Alatalja",
  x2:	"Ristitaljaveto",
  Alaspaino:	"Alaspaino taljassa",
  Deadlift:	"Maastaveto",
  BarbellRow:	"Kulmasoutu",
  DumbbellShoulderPress: "Pystypunnerrus",
  UprightCableRow:	"Pystysoutu",
  DumbbellLateralLiftingFlyes:	"Vipunosto sivulle käsipainoilla",
  DumbbellBentOverLateralRaise:	"Vipunosto olkapään takaosalle",
  FrontDumbbellRaise:	"Vipunosto eteen käsipainoilla",
  BarbellCurl:	"Hauiskääntö",
  DumbbellConcentrationCurl:	"Keskitetty yhden käden hauiskääntö",
  BenchDip:	"Penkkidippi",
  TricepsPushDown:	"Ojentajakääntö",
  CableLyingTricepsExtension:	"Ojentajakääntö maaten taljassa",
	TricepsPushDownWithRope: "Ojentajapunnerrus taljassa",
  Crunch:	"Vatsarutistus maaten",
  LegRaises:	"Jalkojen nosto",
  ABCable:	"Vatsarutistus ristitaljassa",
  BarbellSquat:	"Jalkakyykky",
  HackSquat:	"Hack -kyykky",
  SquatSmith:	"Smith -kyykky",
  LegPress:	"Jalkaprässi",
  LegExtension:	"Reidenojennus",
  SeatedLegCurl:	"Reidenkoukistus istuen",
  LayingLegCurl:	"Reidenkoukistus maaten",
  CableKickback:	"Pakarapotku taljassa",
  StiffLeggedBarbellDeadlift:	"Maastaveto suorin jaloin",
  GluteSquat:	"Jalkakyykky pakaralle",
  BarbellLunges: "Askelkyykky",
  StandingCalfRaise:	"Pohjelaite seisten",
  SeatedCalfRaise:	"Pohjelaite istuen",
  ClosedCableRow: "?",

  others: 'muuta',

};