export default {
    Home: 'Главная' ,
    Profile: 'Профиль' ,
    LogIn: 'Войти',
    Register: "Зарегистрироваться",
    LogInWithFacebook: "Войти через Facebook",
    LogInwithGoogle: "Войти через Google",
    ForgotYourPassword: "Забыл пароль?",
    Doyouwanttostartrightnow:	"Хочешь начать прямо сейчас?",
    PopularPrograms:	"Популярные программы",
    Programs:	"Программы",
    ChooseProgram:	"Выбери программу",
    BrowsePrograms:	"Посмотреть программы",
    SelectYourprogram:	"Выбери свою программу",
    YourProgram: "Твоя программа",
    MakeOwnProgram:	"Создай свою программу",
    Gender:	"Пол",
    Level:	"Уровень", 
    PerWeek:	"в неделю",
    focus:	"Цель",
    Diary:	"Дневник",
    Weight:	"Вес",
    ownWeight: "Свой вес",
    TotalWeight: "Общий вес",
    maxWeight: "Рекордный вес",
    AverageWeight:	"Средний вес",
    Set: "Сет",
    Sets: "Сеты",
    Reps: "Повторы",
    Total: "Всего",
    HowLong: "Длительность",
    YouhaveworkoutToday: "У тебя есть тренировка сегодня",
    YouHaveRestDay: "У тебя день отдыxа",
    Advice: "Совет",
    Addworkout:	"Добавить тренировку",
    Addactivity:	"Добавить упражнение",
    Exercises: 	"Упражнения",
    Exercise: "Упражнение",
    ExercisesThisWeek: "Упражнения на этой неделе",
    ExercisesLibrary: "Библиотека упражнений",
    SearchExercises: "Поиск упражнений",
    All: "Все",
    totalDays: "Всего дней",
    days: "дней",
    weeks: "недель",
    week: "Неделя",
    inWeek: "в неделю",
    muscles: "мышцы",
    isolation:	"Изолирующие",
    basic:	"Базовые",
    chest:	"Грудь",
    back:	"Спина",
    shoulders:	"Плечи",
    biceps:	"Бицепс",
    triceps:	"Трицепс",
    abs:	"Пресс",
    legs:	"Ноги",
    glutes:	"Ягодицы",
    calves:	"Икры",
    Workouts: "Тренировки",
    workoutsFinished:	"Тренировок выполнено",
    exersiscesFinished:	"Упражнений выполнено",
    currentProgram:	"Текущая программа",
    currentLevel:	"Текущий уровень",
    maximumWeight:	"Максимальный вес",
    ViewStatistics:	"Посмотреть статистику",
    AverageWorkoutTime:	"Среднее время тренировки",
    currentExercise:	"Текущее упражнение",
    muscleGroup:	"Мышечная группа",
    upcomingExercise:	"Следующее упражнение",
    Previous: "Предыдущая",
    NextWeek: "Следующая неделя",
    Delete: "Удалить",
    TotalExercises: "Всего упражнений",
    Discover: "Discover",
    WePrepared: 'We prepared a programs that will fit your needs',
    DoneThisWeek: "Done this week",
    DoneThisDay: "Done this day",
    CustomExercises: "Custom exercise",
    ContinueProgram: "Continue program",
    NoData: "No Data Here",
    Logout: "Log out",
    ChangeWeight: "Change weight",
    LeaveProgram: "Leave program",
    LeaveProgramAlert: "You are about to end the program. Are you sure?",
    DiaryPromoTitle: "Record and track achievements",
    DiaryPromo: "A diary will show the statistics for each training day and will inform you about upcoming trainings",
    ExercisesPromoTitle: "Exercises Library",
    ExercisesPromoText: "Find the exercises according to the muscle groups and the type. Additionaly, we have videos, that will help you learn train effectively and safely",
    Cancel: "Cancel" ,
    Add: "Add",
    CheckOut: "Check Out",
    RandomAdvice: "Remember to stretch after the traing to keep muscles in a good shape",
    DailyAdvice: "Daily Advice",
    LoginPromo: "Learn how to train rationally with our library of exercises with explanatory videos.",
    Email: "Email",
    Password: "Password",
    EnterYourEmail: "Enter your email",
    EnterPassword: "Enter your password",
    EnterName: "Enter your name",
    Male: "Male",
    Female: "Female",
    male: 'male',
    female: 'female',
    both: 'both',
    exercisesDone: "Exercises done",
    TotalSets: "Total sets",
    TotalReps: "Toral reps",
    FeedbackText: "Please evaluate the difficulty of the training so that we can adjust the program for you",
    Next: "Next",
    Measurements: "Enter your details",
    HowManyWeeks: "How many days per week you want to train?",
    FillBasic: "Great! Fill the basic information below and you are ready!",
    Done: "Done",
    Height: "Height",
    Name: "Name",
    ExerciseName: "Exercise name",
    EnterExerciseName: "Enter exercise name",
    ProgramsPromo: "All programs are designed by professionals",
    First: "First",
    Second: "Second",
    Third: "Third",
    Fourth: "Fourth",
    Fifth: "Fifth",
    Sixth: "Sixth",
    Seventh: "Seventh",
    Day: "Day",
    WorkoutIsCompleted: "Workout is completed!",
    Feedback: "Feedback",
    Bad: "Hard",
    Fine: "Perfect",
    VeryGood: "Easy",
    SelectWorkoutDays: "Select Workout Days",
    ChooseAtWhatDays: "Please mark the workout days",
    Monday: "Monday",
    Tuesday: "Tuesday",
    Wednesday: "Wednesday",
    Thursday: "Thursday",
    Friday: "Friday",
    Saturday: "Saturday",
    Sunday: "Sunday",
    Save: "Save",
    
  
    EnrollToProgram: "Enroll to program",
    EditProgram: "Edit",
    DoneWorkoutToday: "You have finished workout today",
  
    //Exercises
    ExerciseName: "Exercise name",
    Benchpress:	"Benchpress",
    Inclinedumbbellpress:	"Incline dumbbell press",
    Lyingflyes: "Lying chest fly",
    PecDekFlyes:	"Pec deck flyes",
    Crossover:	"Cable Crossover",
    Chins:	"Chin-Up",
    Latpulldown:	"Lat pull down",
    Seatedcablerow:	"Seated cable row",
    x2:	"Cross over pulley",
    Alaspaino:	"Standing cable pullover",
    Deadlift:	"Deadlift",
    BentoverRow:	"Bent over row",
    ShoulderPress: "Shoulder Press",
    Uprightcablerow:	"Upright cable row",
    Standingdumbbellfly:	"Standing dumbbell fly",
    DumbbellBentOverLateralRaise:	"Dumbbell bent-over raise",
    FrontDumbbellRaise:	"Front dumbbell raise",
    BicepsCurl:	"Biceps curl",
    Concentrationcurl:	"Concentration curl",
    BenchDip:	"Bench dip",
    Tricepspushdown:	"Triceps pushdown",
    Lyingtricepsextensions:	"Lying triceps extensions",
    TricepsPushDownWithRope: "Triceps pushdown (with rope)",
    Crunch:	"Crunch",
    LegRaises:	"Leg raises",
    ABCable:	"Ab Pulldown",
    Squat:	"Squat",
    HackSquat:	"Hack squat",
    SquatSmith:	"Squat smith machine",
    LegPress:	"Leg press",
    Legextensions:	"Leg extensions",
    SeatedLegCurl:	"Seated leg curl",
    Lyinglegcurl:	"Lying leg curl",
    CableKickback:	"Cable kickbacks",
    StiffLeggedBarbellDeadlift:	"Stiff-legged barbell deadlift",
    GluteSquat:	"Glute squat",
    Lunges: "Lunges",
    Standingcalfraise:	"Standing calf raise",
    SeatedCalfRaise:	"Seated calf raise",
    ClosedCableRow: "Closed cable row",
    Legraiseonthebench: "Leg raise on the bench",
    others: 'others',
    all: 'all',
    ShowMore: "Show more",
    Hide: "Hide"
  };