export default {
    Home: 'Главная' ,
    Profile: 'Профиль' ,
    LogIn: 'Войти',
    Register: "Зарегистрироваться",
    LogInWithFacebook: "Войти через Facebook",
    LogInwithGoogle: "Войти через Google",
    ForgotYourPassword: "Забыли пароль?",
    Doyouwanttostartrightnow:	"Хотите начать прямо сейчас?",
    PopularPrograms:	"Популярные программы",
    Programs:	"Программы",
    ChooseProgram:	"Выберите программу",
    BrowsePrograms:	"Просмотреть программы",
    SelectYourprogram:	"Выберите программу",
    YourProgram: "Ваша программа",
    MakeOwnProgram:	"Создайте свою программу",
    Gender:	"Пол",
    Level:	"Уровень", 
    PerWeek:	"в неделю",
    focus:	"Фокус",
    Diary:	"Дневник",
    Weight:	"Вес",
    ownWeight: "Ваш вес",
    TotalWeight: "Всего поднято",
    maxWeight: "Рекордный вес",
    AverageWeight:	"Средний вес",
    Set: "Подход",
    Sets: "Подходы",
    Reps: "Повторы",
    Total: "Всего",
    HowLong: "Длительность",
    YouhaveworkoutToday: "У вас есть тренировка сегодня",
    YouHaveRestDay: "У вас день отдыxа",
    Advice: "Совет",
    Addworkout:	"Добавить тренировку",
    Addactivity:	"Добавить упражнение",
    Exercises: 	"Упражнения",
    Exercise: "Упражнение",
    ExercisesThisWeek: "Упражнения на этой неделе",
    ExercisesLibrary: "Упражнения",
    SearchExercises: "Поиск упражнений",
    All: "Все",
    totalDays: "Всего дней",
    days: "дней",
    weeks: "недель",
    week: "Неделя",
    inWeek: "в неделю",
    muscles: "мышцы",
    isolation:	"Изолирующие",
    basic:	"Базовые",
    chest:	"Грудь",
    back:	"Спина",
    shoulders:	"Плечи",
    biceps:	"Бицепс",
    triceps:	"Трицепс",
    abs:	"Пресс",
    legs:	"Ноги",
    glutes:	"Бедра",
    calves:	"Икры",
    Workouts: "Тренировки",
    workoutsFinished:	"Тренировок выполнено",
    exersiscesFinished:	"Упражнений выполнено",
    currentProgram:	"Текущая программа",
    currentLevel:	"Текущий уровень",
    maximumWeight:	"Максимальный вес",
    ViewStatistics:	"Посмотреть статистику",
    AverageWorkoutTime:	"Среднее время тренировки",
    currentExercise:	"Текущее упражнение",
    muscleGroup:	"Мышечная группа",
    upcomingExercise:	"Следующее упражнение",
    Previous: "Предыдущая",
    NextWeek: "Следующая неделя",
    Delete: "Удалить",
    TotalExercises: "Всего упражнений",
    Discover: "Просмотреть",
    WePrepared: 'Все программы составлены профессионалами, чтобы помочь вам набрать мышечную массу как можно быстрее',
    DoneThisWeek: "Сделано на неделе",
    DoneThisDay: "Сегодня",
    CustomExercises: "Custom exercise",
    ContinueProgram: "Continue program",
    NoData: "Нет данных",
    Logout: "Выйти",
    ChangeWeight: "Изменить вес",
    LeaveProgram: "Покинуть программу",
    LeaveProgramAlert: "Вы покидаете программу. Вы уверены?",
    DiaryPromoTitle: "Record and track achievements",
    DiaryPromo: "Дневник показывает статистику для каждой тренировки и информирует обо всех предстоящих событиях",
    ExercisesPromoTitle: "Упражнения",
    ExercisesPromoText: "Find the exercises according to the muscle groups and the type. Additionaly, we have videos, that will help you learn train effectively and safely",
    Cancel: "Назад" ,
    Add: "Добавить",
    CheckOut: "Отметить",
    RandomAdvice: "Не забывайте разогреваться после тренировок, чтобы держать тело в форме",
    DailyAdvice: "Daily Advice",
    LoginPromo: "Узнайте как тренироваться рационально, используя базу упражнений с поясняяющими видео.",
    Email: "Почта",
    Password: "Пароль",
    EnterYourEmail: "Ваш почтовый адрес",
    EnterPassword: "Укажите пароль",
    EnterName: "Укажите имя",
    Male: "Мужской",
    Female: "Женсий",
    male: 'мужской',
    female: 'женский',
    both: 'Оба',
    exercisesDone: "Упражнений выполнено",
    TotalSets: "Всего подходов",
    TotalReps: "Всего повторов",
    FeedbackText: "Пожалуйста, оцените сложность тренировки, чтобы мы могли адаптировать программу",
    Next: "Дальше",
    Measurements: "Укажите ваши параметры",
    HowManyWeeks: "Сколько дней в неделю вы хотите тренироваться?",
    FillBasic: "Начните тренироваться рациональнее прямо сейчас",
    Done: "Готово",
    Height: "Рост",
    Name: "Имя",
    ExerciseName: "Название упражнения",
    EnterExerciseName: "Введите название упражнения",
    ProgramsPromo: "Все программы были составлены профессионалами",
    First: "Первый",
    Second: "Второй",
    Third: "Третий",
    Fourth: "Четвертый",
    Fifth: "Пятый",
    Sixth: "Шестой",
    Seventh: "Седьмой",
    Day: "День",
    WorkoutIsCompleted: "Тренировка завершена",
    Feedback: "Отзыв",
    Bad: "Тяжело",
    Fine: "Отлично",
    VeryGood: "Легко",
    SelectWorkoutDays: "Выберите дни тренировок",
    ChooseAtWhatDays: "Отметьте дни тренировок",
    Monday: "Понедельник",
    Tuesday: "Вторник",
    Wednesday: "Среда",
    Thursday: "Четверг",
    Friday: "Пятница",
    Saturday: "Суббота",
    Sunday: "Воскресенье",
    Save: "Сохранить",
    
  
    EnrollToProgram: "Выбрать программу",
    EditProgram: "Изменить",
    DoneWorkoutToday: "Вы  уже тренировались сегодня",
  
    //Exercises
    ExerciseName: "название",
    Benchpress:	"Benchpress",
    Inclinedumbbellpress:	"Incline dumbbell press",
    Lyingflyes: "Lying chest fly",
    PecDekFlyes:	"Pec deck flyes",
    Crossover:	"Cable Crossover",
    Chins:	"Chin-Up",
    Latpulldown:	"Lat pull down",
    Seatedcablerow:	"Seated cable row",
    x2:	"Cross over pulley",
    Alaspaino:	"Standing cable pullover",
    Deadlift:	"Deadlift",
    BentoverRow:	"Bent over row",
    ShoulderPress: "Shoulder Press",
    Uprightcablerow:	"Upright cable row",
    Standingdumbbellfly:	"Standing dumbbell fly",
    DumbbellBentOverLateralRaise:	"Dumbbell bent-over raise",
    FrontDumbbellRaise:	"Front dumbbell raise",
    BicepsCurl:	"Biceps curl",
    Concentrationcurl:	"Concentration curl",
    BenchDip:	"Bench dip",
    Tricepspushdown:	"Triceps pushdown",
    Lyingtricepsextensions:	"Lying triceps extensions",
    TricepsPushDownWithRope: "Triceps pushdown (with rope)",
    Crunch:	"Crunch",
    LegRaises:	"Leg raises",
    ABCable:	"Ab Pulldown",
    Squat:	"Squat",
    HackSquat:	"Hack squat",
    SquatSmith:	"Squat smith machine",
    LegPress:	"Leg press",
    Legextensions:	"Leg extensions",
    SeatedLegCurl:	"Seated leg curl",
    Lyinglegcurl:	"Lying leg curl",
    CableKickback:	"Cable kickbacks",
    StiffLeggedBarbellDeadlift:	"Stiff-legged barbell deadlift",
    GluteSquat:	"Glute squat",
    Lunges: "Lunges",
    Standingcalfraise:	"Standing calf raise",
    SeatedCalfRaise:	"Seated calf raise",
    ClosedCableRow: "Closed cable row",
    Legraiseonthebench: "Leg raise on the bench",
    others: 'другие',
    all: 'все',
    ShowMore: "Больше",
    Hide: "Скрыть"
  };